name: Sync with Hugging Face Repo

on:
    push:
        branches:
            [main, develop]
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Sync with Hugging Face
              uses: nateraw/huggingface-sync-action@v0.0.4
              with:
                  github_repo_id: HaarisIqubal/summarize_doc
                  huggingface_repo_id: HaarisIqubal/summarize_documents
                  repo_type: space
                  space_sdk: streamlit
                  hf_token: ${{ secrets.HF_TOKEN }}
